name: "Release"
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.8
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        ignore_dev_requirements: true
