name: Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8'
      - uses: atu4403/poetry-setup-multi-platform@v1
      - name: Install dependencies with poetry
        run: |
          poetry --version
          poetry install
        shell: bash
      - name: Test with pytest
        run: poetry run pytest
        shell: bash
      - name: Lint with black
        run: poetry run black --check --diff --color .
        shell: bash
