name: "Test"

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
jobs:
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pytest-args:
          - tests/test_pfrl_2019_wrappers.py
          - tests/test_pfrl_2020_wrappers.py
          - -k MineRLTreechop-v0
          - -k MineRLNavigate-v0
          - -k MineRLNavigateDense-v0
          - -k MineRLNavigateExtreme-v0
          - -k MineRLNavigateExtremeDense-v0
          - -k MineRLObtainDiamond-v0
          - -k MineRLObtainDiamondDense-v0
          - -k MineRLObtainIronPickaxe-v0
          - -k MineRLObtainIronPickaxeDense-v0
          - -k MineRLTreechopVectorObf-v0
          - -k MineRLNavigateVectorObf-v0
          - -k MineRLNavigateDenseVectorObf-v0
          - -k MineRLNavigateExtremeVectorObf-v0
          - -k MineRLNavigateExtremeDenseVectorObf-v0
          - -k MineRLObtainDiamondVectorObf-v0
          - -k MineRLObtainDiamondDenseVectorObf-v0
          - -k MineRLObtainIronPickaxeVectorObf-v0
          - -k MineRLObtainIronPickaxeDenseVectorObf-v0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Cached Docker Image
        uses: actions/cache@v2
        with:
          path: /tmp/image.tar
          key: ${{ runner.os }}-image-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-image-
      - name: Load Docker Image
        run: |
          docker load --input /tmp/image.tar
      - name: Lint with black
        run: |
          docker run --rm -i \
          -v $(pwd):/minerl-wrappers \
          minerl-wrappers:latest \
          poetry run black --check --diff --color .
        shell: bash
      - name: Test with pytest
        run: |
          docker run --rm -i \
          -v $(pwd):/minerl-wrappers \
          minerl-wrappers:latest \
          poetry run pytest ${{ matrix.pytest-args }} --cov=minerl_wrappers --cov-report xml:coverage.xml
        shell: bash
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: true