name: "Docker CI"

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Cache Docker Image
        uses: actions/cache@v2
        with:
          path: /tmp/image.tar
          key: ${{ runner.os }}-image-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-image-
      - name: Build Dependencies Image
        run: |
          docker buildx build \
          --target test \
          -t minerl-wrappers:latest \
          --cache-from type=local,src=/tmp/.buildx-cache \
          --cache-to type=local,dest=/tmp/.buildx-cache-new \
          --output type=docker,dest=- . > /tmp/image-new.tar
        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          rm -rf /tmp/image.tar
          mv /tmp/image-new.tar /tmp/image.tar
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pytest-args:
          - tests/test_pfrl_2019_wrappers.py
          - tests/test_pfrl_2020_wrappers.py
          - -k MineRLTreechop-v0
          - -k MineRLNavigate-v0
          - -k MineRLNavigateDense-v0
          - -k MineRLNavigateExtreme-v0
          - -k MineRLNavigateExtremeDense-v0
          - -k MineRLObtainDiamond-v0
          - -k MineRLObtainDiamondDense-v0
          - -k MineRLObtainIronPickaxe-v0
          - -k MineRLObtainIronPickaxeDense-v0
          - -k MineRLTreechopVectorObf-v0
          - -k MineRLNavigateVectorObf-v0
          - -k MineRLNavigateDenseVectorObf-v0
          - -k MineRLNavigateExtremeVectorObf-v0
          - -k MineRLNavigateExtremeDenseVectorObf-v0
          - -k MineRLObtainDiamondVectorObf-v0
          - -k MineRLObtainDiamondDenseVectorObf-v0
          - -k MineRLObtainIronPickaxeVectorObf-v0
          - -k MineRLObtainIronPickaxeDenseVectorObf-v0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Cached Docker Image
        uses: actions/cache@v2
        with:
          path: /tmp/image.tar
          key: ${{ runner.os }}-image-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-image-
      - name: Load Docker Image
        run: |
          docker load --input /tmp/image.tar
      - name: Lint with black
        run: |
          docker run --rm -i minerl-wrappers:latest \
          poetry run black --check --diff --color .
        shell: bash
      - name: Test with pytest
        run: |
          docker run --rm -i -v $(pwd)/cov:/minerl-wrappers/cov minerl-wrappers:latest \
          poetry run pytest ${{ matrix.pytest-args }} --cov=minerl_wrappers --cov-report xml:cov/coverage.xml
        shell: bash
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: true